Repository CDH-Studio/I-Talent, pull requests merged in 2020-12, with the labels that each got.

#1039 [Fix] Search Filter - Results page accessibility
  services/frontend/src/components/searchFilter/SearchFilterView.jsx
  services/frontend/src/i18n/en_CA.json
  services/frontend/src/i18n/fr_CA.json
Labels: accessibility

#1088 [Fix] Results header not shown when page accessed through URL
  services/frontend/src/components/layouts/resultsLayout/ResultLayout.jsx
  services/frontend/src/components/layouts/statsLayout/StatsLayout.jsx
  services/frontend/src/components/resultsCard/ResultsCard.jsx
  services/frontend/src/components/resultsCard/ResultsCardView.jsx
  services/frontend/src/pages/Results.jsx
Labels: fix

#1147 [Fix] Fixes result's card matched criteria modal not opening from enter key press on button
  services/frontend/src/components/resultsCard/resultProfileCard/ResultProfileCardView.jsx
  services/frontend/src/i18n/en_CA.json
  services/frontend/src/i18n/fr_CA.json
Labels: fix

#1140 [Fix] Remove select all option for Skills and Mentorship Skills dropdowns
  services/frontend/package.json
  services/frontend/src/components/profileForms/talentForm/TalentForm.jsx
  services/frontend/src/components/profileForms/talentForm/TalentFormView.jsx
  services/frontend/src/components/searchBar/SearchBar.jsx
  services/frontend/src/components/searchBar/SearchBarView.jsx
  services/frontend/src/components/searchFilter/SearchFilter.jsx
  services/frontend/src/components/searchFilter/SearchFilterView.jsx
  services/frontend/yarn.lock
Labels: UX, enhancement

#1182 [Fix] advanced search for classification, location, skills, and mentorship
  services/frontend/src/components/searchFilter/SearchFilterView.jsx
Labels: bug, high priority
