Repository CDH-Studio/I-Talent, pull requests merged in 2020-04, with the labels that each got.

#112 [New] Implemented New Logo & Landing Page
  services/frontend-v3/public/favicon.ico
  services/frontend-v3/src/App.css
  services/frontend-v3/src/App.js
  services/frontend-v3/src/assets/MyTalent-Logo-Full-v2-dark.svg
  services/frontend-v3/src/assets/MyTalent-Logo-Full-v2.svg
  services/frontend-v3/src/assets/MyTalent-Logo-Full.svg
  services/frontend-v3/src/assets/landing-1.svg
  services/frontend-v3/src/assets/landing-2.svg
  services/frontend-v3/src/assets/landing-3.svg
  services/frontend-v3/src/components/layouts/appLayout/AppLayoutView.jsx
  services/frontend-v3/src/components/layouts/appLayout/topNav/TopNavView.jsx
  services/frontend-v3/src/components/layouts/createProfileLayout/CreateProfileLayout.jsx
  services/frontend-v3/src/components/layouts/landingLayout/LandingLayout.jsx
  services/frontend-v3/src/components/layouts/landingLayout/LandingLayoutView.jsx
  services/frontend-v3/src/components/searchBar/SearchBarView.jsx
  services/frontend-v3/src/pages/Landing.js
  services/frontend-v3/src/pages/LandingPage.jsx
  services/frontend-v3/src/pages/index.js
Labels: New Feature

#110 [Fix] Add french form options
  services/backend/API/options/get.js
  services/frontend-v3/src/components/layouts/appLayout/AppLayout.jsx
  services/frontend-v3/src/components/layouts/appLayout/AppLayoutView.jsx
  services/frontend-v3/src/components/layouts/appLayout/topNav/TopNav.jsx
  services/frontend-v3/src/components/layouts/appLayout/topNav/TopNavView.jsx
  services/frontend-v3/src/components/layouts/createProfileLayout/CreateProfileLayout.jsx
  services/frontend-v3/src/components/layouts/createProfileLayout/CreateProfileLayoutView.jsx
  services/frontend-v3/src/components/layouts/editProfileLayout/EditProfileLayout.jsx
  services/frontend-v3/src/components/layouts/editProfileLayout/EditProfileLayoutView.jsx
  services/frontend-v3/src/components/profileForms/employmentDataForm/EmploymentDataForm.jsx
  services/frontend-v3/src/components/profileForms/employmentDataForm/EmploymentDataFormView.jsx
  services/frontend-v3/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx
  services/frontend-v3/src/components/profileForms/personalGrowthForm/PersonalGrowthForm.jsx
  services/frontend-v3/src/components/profileForms/personalGrowthForm/PersonalGrowthFormView.jsx
  services/frontend-v3/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx
  services/frontend-v3/src/components/profileForms/qualificationsForm/QualificationsFormView.jsx
  services/frontend-v3/src/components/profileForms/qualificationsForm/educationForm/EducationForm.jsx
  services/frontend-v3/src/components/profileForms/qualificationsForm/educationForm/EducationFormView.jsx
  services/frontend-v3/src/components/profileForms/qualificationsForm/experienceForm/ExperienceFormView.jsx
  services/frontend-v3/src/components/profileForms/talentForm/TalentForm.jsx
  services/frontend-v3/src/components/profileForms/talentForm/TalentFormView.jsx
  services/frontend-v3/src/i18n/en_CA.json
  services/frontend-v3/src/i18n/fr_CA.json
  services/frontend-v3/src/pages/ProfileCreate.jsx
  services/frontend-v3/src/pages/ProfileEdit.jsx
Labels: Fix

#113 [Fix] fix experience form title
  services/frontend-v3/src/components/profileForms/qualificationsForm/QualificationsFormView.jsx
Labels: Fix

#114 [New] Make Sidebar Steps Clickable
  services/frontend-v3/src/components/layouts/createProfileLayout/CreateProfileLayoutView.jsx
  services/frontend-v3/src/components/layouts/editProfileLayout/EditProfileLayoutView.jsx
  services/frontend-v3/src/components/sideNav/SideNavView.jsx
  services/frontend-v3/src/i18n/en_CA.json
  services/frontend-v3/src/i18n/fr_CA.json
Labels: New Feature

#117 [New] Added Finished Step For Setup
  services/frontend-v3/src/components/layouts/createProfileLayout/CreateProfileLayoutView.jsx
  services/frontend-v3/src/components/profileForms/doneSetup/DoneSetup.jsx
  services/frontend-v3/src/components/profileForms/doneSetup/DoneSetupView.jsx
  services/frontend-v3/src/components/profileForms/employmentDataForm/EmploymentDataFormView.jsx
  services/frontend-v3/src/components/profileForms/index.js
  services/frontend-v3/src/components/profileForms/langProficiencyForm/LangProficiencyFormView.jsx
  services/frontend-v3/src/components/profileForms/personalGrowthForm/PersonalGrowthFormView.jsx
  services/frontend-v3/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx
  services/frontend-v3/src/components/profileForms/qualificationsForm/QualificationsFormView.jsx
  services/frontend-v3/src/components/profileForms/talentForm/TalentFormView.jsx
  services/frontend-v3/src/components/profileForms/welcome/WelcomeView.jsx
  services/frontend-v3/src/components/sideNav/SideNavView.jsx
  services/frontend-v3/src/i18n/en_CA.json
  services/frontend-v3/src/i18n/fr_CA.json
Labels: New Feature

#111 [New] Added competencies table/page
  services/frontend-v3/src/components/competencyTable/CompetencyTable.jsx
  services/frontend-v3/src/components/competencyTable/CompetencyTableView.jsx
  services/frontend-v3/src/i18n/en_CA.json
  services/frontend-v3/src/i18n/fr_CA.json
  services/frontend-v3/src/pages/admin/Competency.jsx
Labels: New Feature

#118 [New] Update antd 4.1.4
  services/frontend-v3/package.json
  services/frontend-v3/yarn.lock
Labels: dependencies

#106 [New] Add keycloak prod config to UAT web app
  env/backend.env.example
  env/web.env.example
  services/backend/keycloak.json
  services/backend/util/keycloak.js
  services/frontend-v3/public/keycloak.json
  services/frontend-v3/src/keycloak.js
  services/frontend-v3/src/routes/Admin.js
  services/frontend-v3/src/routes/Secured.js
Labels: New Feature

#131 [New] Created Admin Schools Table/Page
  services/frontend-v3/src/components/layouts/adminLayout/AdminLayoutView.jsx
  services/frontend-v3/src/components/schoolTable/SchoolTable.jsx
  services/frontend-v3/src/components/schoolTable/SchoolTableView.jsx
  services/frontend-v3/src/i18n/en_CA.json
  services/frontend-v3/src/i18n/fr_CA.json
  services/frontend-v3/src/pages/admin/School.jsx
  services/frontend-v3/src/pages/admin/index.js
  services/frontend-v3/src/routes/Admin.js
Labels: New Feature, UX

#142 [Fix] Updated README.md
  README.md
  docs/wikiFiles/I-Talent-page.jpg
Labels: Fix

#143 [Fix] Fixed Screenshot not appearing on README.md
  README.md
Labels: Fix
